AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  SAM Template for GetProducts microservice

Globals:
  Function:
    Timeout: 3

Resources:
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Products
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3

  GetProductsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: GetProductsDynamoDB
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Scan
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt ProductsTable.Arn

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/get_products/
      Handler: get_products.lambda_handler
      Runtime: python3.12
      Role: !GetAtt GetProductsExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api
          Properties:
            Path: /get_products
            Method: get

Outputs:
  MicroserviceApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  GetProductsFunction:
    Description: "GetProducts Lambda Function ARN"
    Value: !GetAtt GetProductsFunction.Arn
  EndpointForGetProducts:
    Description: "GetProducts API endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/get_products/"
